# Generated by Django 4.2.9 on 2026-04-04 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('current_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('previous_close', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('market_cap', models.BigIntegerField(default=0)),
                ('change_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('high_52_week', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('low_52_week', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('user', 'Regular User')], default='user', max_length=10)),
                ('bio', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('notification_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('VOLATILITY', 'Volatility'), ('RSI', 'Relative Strength Index'), ('TREND', 'Trend Analysis'), ('BREAKOUT', 'Breakout Detection'), ('PORTFOLIO', 'Portfolio Analysis')], max_length=20)),
                ('result_data', models.JSONField(default=dict)),
                ('parameters', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='stocks.stock')),
            ],
            options={
                'verbose_name': 'Analytics Result',
                'verbose_name_plural': 'Analytics Results',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('PRICE_ABOVE', 'Price Above'), ('PRICE_BELOW', 'Price Below'), ('VOLUME_ABOVE', 'Volume Above'), ('CHANGE_ABOVE', 'Change % Above'), ('CHANGE_BELOW', 'Change % Below')], max_length=20)),
                ('threshold', models.DecimalField(decimal_places=4, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('disabled', 'Disabled')], default='active', max_length=12)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(blank=True, default='')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist Entry',
                'verbose_name_plural': 'Watchlist Entries',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
